package com.example.springboot.controller;
import com.example.springboot.model.Country;
import com.example.springboot.repository.CountryRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.util.Collection;
import java.util.List;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/index") // This means URL's start with /demo (after Application path)
public class CountryController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CountryRepository countryRepository;


    @GetMapping(path = "/allCountries")
    public @ResponseBody
    Iterable<Country> allCountries() {
        // This returns a JSON or XML with the users
        Collection<Country> countryList =  countryRepository.allCountries();
        return countryList;
    }

    @GetMapping(path = "/allCountriesNames")
    public @ResponseBody
    Iterable<String> getAllCountriesNames() {
        // This returns a JSON or XML with the users
        Collection<String> countryList =  countryRepository.getAllCountries();
        return countryList;
    }

     @GetMapping(path = "/register1")
    public String showForm(Model model) {
        Country country = new Country();
        model.addAttribute("country", country);

        List<String> countryList = (List<String>) countryRepository.getAllCountries();
        model.addAttribute("countryList", countryList);

        return "register_form";
    }


}