package com.example.springboot.controller;
import com.example.springboot.model.City;
import com.example.springboot.model.Country;
import com.example.springboot.model.Hotel;
import com.example.springboot.model.Review;
import com.example.springboot.repository.CityRepository;
import com.example.springboot.repository.CountryRepository;
import com.example.springboot.repository.HotelRepository;
import com.example.springboot.repository.ReviewRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;
import java.util.Collection;
import java.util.List;

@Controller // This means that this class is a Controller
public class CountryController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CountryRepository countryRepository;
    @Autowired
    private CityRepository cityRepository;

    @Autowired
    private HotelRepository hotelRepository;
    @Autowired
    private ReviewRepository reviewRepository;

    @GetMapping("/findHotelReviews")
    public String showForm(Model model) {
        model.addAttribute("activePage","findHotelReviews");
        Country country = new Country();
        model.addAttribute("country", country);

        List<Country> countryList = (List<Country>) countryRepository.findAll();
        model.addAttribute("countryList", countryList);

        City city = new City();
        model.addAttribute("city", city);

        List<City> cityList = (List<City>) cityRepository.findAll();
        model.addAttribute("cityList", cityList);

        Hotel hotel = new Hotel();
        model.addAttribute("hotel", hotel);

        List<Hotel> hotelList = (List<Hotel>) hotelRepository.findAll();
        model.addAttribute("hotelList", hotelList);

        /*List<Review> reviewsList = (List<Review>) reviewRepository.findAll();
        model.addAttribute("reviews", reviewsList);*/
        return "findHotelReviews";
    }

    @PostMapping("/chooseCountry")
    public String greetingSubmit(@ModelAttribute Country selectedCountry, Model model) {
        Country country = new Country();
        model.addAttribute("country", country);

        List<Country> countryList = (List<Country>) countryRepository.findAll();
        model.addAttribute("countryList", countryList);

        City city = new City();
        model.addAttribute("city", city);

        List<City> cityList = (List<City>) cityRepository.getAllCitiesByCountryId(Integer.parseInt(selectedCountry.getName()));
        model.addAttribute("cityList", cityList);

        Hotel hotel = new Hotel();
        model.addAttribute("hotel", hotel);

        List<Hotel> hotelList = (List<Hotel>) hotelRepository.findAll();
        model.addAttribute("hotelList", hotelList);
        return "findHotelReviews";
    }
}