package com.example.springboot.controller;

import com.example.springboot.model.Hotel;
import com.example.springboot.repository.HotelRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/index") // This means URL's start with /demo (after Application path)
public class HotelController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private HotelRepository hotelRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewHotel(@RequestParam int id, @RequestParam String name
            , @RequestParam String address, @RequestParam int cityId) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Hotel hotel = new Hotel();
        hotel.setId(id);
        hotel.setName(name);
        hotel.setAddress(address);
        hotel.setCity_id(cityId);
        hotelRepository.save(hotel);
        return "Saved new hotel";
    }

    @GetMapping(path = "/allHotels")
    public @ResponseBody
    Iterable<Hotel> getAllHotels() {
        // This returns a JSON or XML with the users
        return hotelRepository.findAll();
    }
    @GetMapping(path = "/allHotelsNames")
    public @ResponseBody
    Iterable<String> getAllHotelsNames() {
        // This returns a JSON or XML with the users
        return hotelRepository.getAllHotelsNames();
    }
}